### ISSUE TITLE
Implement CASF-16 "scoring-power" function

### ISSUE THREAD

**Issue by NiklasTR** [labdao/casf-2016-eval#2]

**Comment by NiklasTR** [comment]
screening power calculation works:

![Image](https://user-images.githubusercontent.com/18559148/214292031-8bead596-76fc-4d09-8e6b-77a48aee3265.png)

![Image](https://user-images.githubusercontent.com/18559148/214291976-4a351aee-8f5f-4cf3-af9e-81ab1ffad91d.png)

Now need to make sure that we can read scoring function output systematically. This is the expected file format for running on CASF-16 core:

#code	score
1a30	-214796
1bcu	-159418
1bzc	-268915
1c5z	-134235
1e66	-233559

Where code is the name of the core-set directory. For example: casf-2016-eval/data/coreset/1a30
with the content

drwxrwxr-x@   8 rindtorff  staff   256B Dec 10  2018 .
drwxrwxr-x@ 288 rindtorff  staff   9.0K Jan 23 11:58 ..
-rw-rw-r--@   1 rindtorff  staff   5.6K Oct 12  2018 1a30_ligand.mol2
-rw-r--r--@   1 rindtorff  staff   3.6K Oct 24  2018 1a30_ligand.sdf
-rw-rw-r--@   1 rindtorff  staff   5.6K Oct 24  2018 1a30_ligand_opt.mol2
-rw-r--r--@   1 rindtorff  staff    34K Oct 24  2018 1a30_pocket.pdb
-rw-r--r--@   1 rindtorff  staff   384K Oct 24  2018 1a30_protein.mol2
-rw-r--r--@   1 rindtorff  staff   249K Oct 12  2018 1a30_protein.pdb

**Comment by thetechnocrat-dev** [comment]
https://github.com/labdao/casf-2016-evaluator
